"""Deterministic synthetic sequence data (Tier 0 fixture).

No downloads, no licenses, no tokens: the corpus is generated by a seeded linear congruential
generator, so it is reproducible from the config alone and its checksum can be recorded in a run
manifest. This is the Tier-0/1 data source; WikiText-2 and pretrained tokenizers belong to the
Tier-2 pipeline that is not implemented (see ``docs/research/preregistration.md``).
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass

import torch

from spectraquant.config import DataConfig

__all__ = ["SyntheticCorpus", "build_corpus", "sequence_checksum"]


@dataclass(frozen=True)
class SyntheticCorpus:
    """A train/validation split of integer token sequences.

    Attributes:
        train: ``(n_train, seq_len + 1)`` int64 tensor; ``[:, :-1]`` are inputs, ``[:, 1:]`` targets.
        val: ``(n_val, seq_len + 1)`` int64 tensor, disjoint start tokens from ``train``.
        vocab_size: number of distinct tokens.
        checksum: ``sha256:<hex>`` over the concatenated raw bytes of both splits.
        train_start: LCG start token used for the training split.
        val_start: LCG start token used for the validation split.
    """

    train: torch.Tensor
    val: torch.Tensor
    vocab_size: int
    checksum: str
    train_start: int
    val_start: int

    @property
    def seq_len(self) -> int:
        """Number of predicted positions per sequence."""
        return int(self.train.shape[1]) - 1


def _sequences(
    cfg: DataConfig,
    *,
    n_sequences: int,
    start_token: int,
    generator: torch.Generator,
) -> torch.Tensor:
    """Generate ``n_sequences`` rows of ``seq_len + 1`` tokens from the configured recurrence.

    The default generator is ``token_{n+1} = (lcg_a * token_n + lcg_b) mod vocab_size``, a fully
    deterministic function of the previous token: a model that learns the transition table can
    drive the loss well below the uniform-prior entropy ``log(vocab_size)``.
    """
    if cfg.generator != "lcg":
        raise NotImplementedError(
            f"data.generator={cfg.generator!r} is not implemented; only 'lcg' exists in the "
            "Tier-0/1 scaffold"
        )
    if start_token < 0 or start_token >= cfg.vocab_size:
        raise ValueError(f"start_token must be in [0, {cfg.vocab_size}), got {start_token}")
    if start_token + n_sequences > cfg.vocab_size:
        raise ValueError(
            "the disjoint-start-token split needs "
            f"start_token + n_sequences <= vocab_size, got {start_token} + {n_sequences} > "
            f"{cfg.vocab_size}"
        )

    # A seeded permutation of the disjoint start-token window: the corpus depends on the seed, yet
    # train and validation rows can never share a start token.
    offsets = torch.randperm(n_sequences, generator=generator)
    rows = torch.empty((n_sequences, cfg.seq_len + 1), dtype=torch.long)
    rows[:, 0] = (start_token + offsets) % cfg.vocab_size
    for position in range(cfg.seq_len):
        rows[:, position + 1] = (cfg.lcg_a * rows[:, position] + cfg.lcg_b) % cfg.vocab_size
    return rows


def sequence_checksum(*tensors: torch.Tensor) -> str:
    """Return ``sha256:<hex>`` over the concatenated bytes of the given tensors."""
    digest = hashlib.sha256()
    for tensor in tensors:
        digest.update(tensor.detach().cpu().contiguous().numpy().tobytes())
    return f"sha256:{digest.hexdigest()}"


def build_corpus(cfg: DataConfig, *, seed: int) -> SyntheticCorpus:
    """Build the deterministic corpus described by ``cfg``.

    Args:
        cfg: validated data config.
        seed: seed for the (unused-in-practice, kept for interface stability) sampling generator.

    Returns:
        A :class:`SyntheticCorpus` with train/val splits that share no start token.
    """
    generator = torch.Generator().manual_seed(int(seed))
    train = _sequences(
        cfg,
        n_sequences=cfg.n_train_sequences,
        start_token=cfg.train_start,
        generator=generator,
    )
    val = _sequences(
        cfg,
        n_sequences=cfg.n_val_sequences,
        start_token=cfg.val_start,
        generator=generator,
    )
    return SyntheticCorpus(
        train=train,
        val=val,
        vocab_size=cfg.vocab_size,
        checksum=sequence_checksum(train, val),
        train_start=cfg.train_start,
        val_start=cfg.val_start,
    )
