#!/usr/bin/env python
"""Generate the published tables and figures from the committed artifacts.

Every file under ``reports/tables/`` and ``reports/figures/`` is produced *only* by this script,
which reads the committed JSON artifacts under ``artifacts/sample-results/``. Nothing is typed by
hand, so a table or figure cannot drift from the artifact it summarises: re-running the script (or
the regression test ``tests/unit/test_release_artifacts.py``) reproduces the committed bytes.

The script is pure standard library and deterministic; it contains no timestamps, no RNG and no
network access. The Pareto figure is emitted as SVG so that no plotting dependency is added.

Usage::

    uv run python scripts/reproduce/generate_release_artifacts.py            # write committed paths
    uv run python scripts/reproduce/generate_release_artifacts.py --out DIR  # write to DIR instead

Measurement-class and substrate labels are carried through verbatim from each artifact; see
``AGENTS.md`` section 5 for the taxonomy.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
ARTIFACT_ROOT = REPO_ROOT / "artifacts" / "sample-results"
DEFAULT_OUT = REPO_ROOT / "reports"

# Artifact paths (relative to the artifact root) are quoted in every generated file header so a
# reader can trace each number back to its source document.
PROXY_VALIDATION = "proxy-validation/proxy-validation.json"
PROXY_FIXTURE = "proxy-fixture/proxy-fixture.json"
FRONTIER = "allocation-frontier/frontier.json"
CLASS4CPU = "class4cpu/class4cpu.json"
REGULARIZER = "regularizer/sweep.json"

_SOLVER_ORDER = ("uniform", "greedy", "ortools")
_SOLVER_COLORS = {"uniform": "#1f77b4", "greedy": "#ff7f0e", "ortools": "#2ca02c"}
_VARIANT_ORDER = (
    "weight_frobenius",
    "weight_magnitude",
    "activation_magnitude",
    "per_layer_output_error",
    "in_situ_output_error",
    "gain_aware_composed",
    "hessian_diag",
    "quant_residual_stats",
    "spectral_summary",
    "combined",
)


def _load(relative: str) -> dict[str, Any]:
    with (ARTIFACT_ROOT / relative).open(encoding="utf-8") as handle:
        return json.load(handle)


def _num(value: float | int | None, digits: int = 6) -> str:
    """Format a number deterministically at ``digits`` significant figures."""
    if value is None:
        return "n/a"
    if isinstance(value, int) or float(value).is_integer():
        return str(int(value))
    return f"{value:.{digits}g}"


def _mean_sd(metrics: dict[str, Any], key: str) -> str:
    entry = metrics[key]
    return f"{entry['mean']:.6g} +/- {entry['std']:.4g}"


def _banner(title: str, artifact: str, note: str) -> str:
    return (
        f"<!-- Generated by scripts/reproduce/generate_release_artifacts.py from "
        f"artifacts/sample-results/{artifact}. Do not edit by hand. -->\n\n"
        f"# {title}\n\n"
        f"{note}\n"
    )


# --------------------------------------------------------------------------------------------
# Tables
# --------------------------------------------------------------------------------------------
def table_proxy_ranking() -> str:
    doc = _load(PROXY_VALIDATION)
    plan = doc["plan"]
    predeclared = doc["predeclared_mde"]
    lines = [
        _banner(
            "Proxy-ranking table (Milestone 4, local fixture)",
            PROXY_VALIDATION,
            f"Substrate `{doc['substrate']}`; measurement class **{doc['measurement_class']}** "
            f"(fake-quantization quality). Seeds {doc['runs']['seeds']} x cells {plan['cells']} x "
            f"fixtures {plan['fixtures']}; statistical unit: **{doc['statistical_unit']}**. "
            f"Predeclared MDE(z) {predeclared['mde_z_optimistic']} "
            f"(n_eff={predeclared['n_eff_optimistic']}) to {predeclared['mde_z_conservative']} "
            f"(n_eff={predeclared['n_eff_conservative']}) at S={predeclared['seeds']} seeds. "
            "Deltas are candidate minus comparator Fisher-z; the verdict follows the analytic "
            "random-effects CI.",
        ),
        "## 1. Per-cell Spearman rho (mean over seeds, model-level, vs single-layer damage)",
        "",
        "| fixture | rank | bits | " + " | ".join(f"`{v}`" for v in _VARIANT_ORDER) + " |",
        "|---|---|---|" + "---|" * len(_VARIANT_ORDER),
    ]
    for cell in doc["per_cell"]:
        values = " | ".join(f"{cell['variants'][v]['rho_mean']:+.3f}" for v in _VARIANT_ORDER)
        lines.append(f"| {cell['fixture']} | {cell['rank']} | {cell['bits']} | {values} |")
    lines += [
        "",
        "## 2. Model-level aggregation (Fisher-z random effects over clusters)",
        "",
        "| fixture group | candidate | rho_mean | z pooled | z CI | k units | n_eff mean | "
        "achieved MDE(z) |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for group in ("layernorm", "no_layernorm", "all_fixtures"):
        block = doc["aggregate"][group]
        for name in _VARIANT_ORDER:
            variant = block["variants"][name]
            lines.append(
                f"| {group} | `{name}` | {variant['rho_mean']:+.4f} | "
                f"{variant['pooled']:+.4f} | [{variant['ci'][0]:+.4f}, {variant['ci'][1]:+.4f}] | "
                f"{variant['k']} | {variant['n_eff_mean']:+.3f} | {block['mde']['achieved_z']:+.4f} |"
            )
    lines += [
        "",
        "## 3. Predeclared candidate contrasts (candidate minus comparator)",
        "",
        "| fixture group | candidate | comparator | delta_z | random-effects CI | p | verdict |",
        "|---|---|---|---|---|---|---|",
    ]
    comparators = [*plan["predeclared_comparators"], plan["naive_baseline"]]
    for group in ("layernorm", "no_layernorm", "all_fixtures"):
        block = doc["aggregate"][group]
        for candidate in ("combined", "gain_aware_composed"):
            contrasts = block["contrasts"][candidate]
            for comparator in comparators:
                entry = contrasts[comparator]
                lines.append(
                    f"| {group} | `{candidate}` | `{comparator}` | {entry['delta_z']:+.4f} | "
                    f"[{entry['ci'][0]:+.4f}, {entry['ci'][1]:+.4f}] | {_num(entry['p_value'])} | "
                    f"{entry['verdict']['verdict']} |"
                )
    lines += [
        "",
        "## 4. Cloud confirmatory cells",
        "",
        "| cell | hypothesis | tier | substrate | status |",
        "|---|---|---|---|---|",
    ]
    for cell in doc["cloud_cells"].values():
        lines.append(
            f"| {cell['confirmatory_cell']} | {cell['hypothesis']} | {cell['tier']} | "
            f"`{cell['substrate']}` | **{cell['status']}** |"
        )
    lines += [
        "",
        "Every number above is class "
        f"{doc['measurement_class']} on the `{doc['substrate']}` substrate; no storage, kernel or "
        "latency claim is made here.",
        "",
    ]
    return "\n".join(lines)


def table_allocator_frontier() -> str:
    doc = _load(FRONTIER)
    classes = doc["measurement_classes"]
    lines = [
        _banner(
            "Allocator frontier table (Milestone 6, local fixture)",
            FRONTIER,
            f"Substrate `{doc['substrate']}`; {doc['scope']}. Classes: accounted_bytes="
            f"{classes['accounted_bytes']}, measured_bytes={classes['measured_bytes']}, "
            f"predicted_error={classes['predicted_error']}, measured_hidden_damage="
            f"{classes['measured_hidden_damage']}. Compression grid: ranks {doc['compression']['ranks']},"
            f" bits {doc['compression']['bits']}, group_size {doc['compression']['group_size']}, "
            f"serializer `{doc['compression']['serializer']}`.",
        ),
        "| budget B (class 1) | solver | accounted B | measured B (class 3) | rel diff | "
        "predicted error (class 2) | hidden damage (class 2) | logits damage (class 2) | "
        "mean rank | mean bits | distinct options |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for point in doc["points"]:
        for solver in _SOLVER_ORDER:
            arm = point["arms"][solver]
            parity = arm["byte_parity"]
            lines.append(
                f"| {point['budget_bytes']} | {solver} | {arm['accounted_bytes']} | "
                f"{arm['measured_bytes']} | {parity['relative_difference']:.2e} | "
                f"{arm['predicted_error']:.6e} | {arm['measured_hidden_damage']:.6f} | "
                f"{arm['measured_logits_damage']:.6f} | {arm['mean_rank']:.4f} | "
                f"{arm['mean_bits']:.4f} | {arm['distinct_options']} |"
            )
    recon = doc["byte_reconciliation"]
    rank = doc["rank_agreement"]
    lines += [
        "",
        "## Equal-memory wins (uniform reference vs mixed arm, same measured bytes)",
        "",
        "| budget B | candidate | hidden damage (candidate) | hidden damage (uniform) | ratio |",
        "|---|---|---|---|---|",
    ]
    for win in doc["equal_memory_wins"]:
        lines.append(
            f"| {win['budget_bytes']} | {win['candidate']} | {win['hidden_damage_candidate']:.6f} | "
            f"{win['hidden_damage_reference']:.6f} | {win['hidden_damage_ratio']:.6f} |"
        )
    lines += [
        "",
        "## Byte reconciliation and rank agreement",
        "",
        f"- byte reconciliation: `max_relative_difference = "
        f"{recon['max_relative_difference']}` over {recon['n_reconciliations']} configurations; "
        f"`all_within_tolerance = {str(recon['all_within_tolerance']).lower()}`; "
        f"`total_container_overhead_bytes = {recon['total_container_overhead_bytes']}`.",
        f"- predicted-vs-measured rank agreement across all arms: Spearman "
        f"`{rank['across_all_arms_spearman']}`; per-arm layer Spearman mean "
        f"`{rank['per_arm_layer_spearman_mean']}`; per solver {rank['per_solver_spearman']}.",
        f"- H4 confirmatory cell: **{doc['h4']['confirmatory_cell']}** "
        f"(`{doc['h4']['confirmatory_cell_detail']}`).",
        f"- HAWQ-V2-style bit-only comparator: {doc['h4']['bit_only_comparator']}.",
        "",
        "Hidden damage is the proxy's target (the final hidden state); logits damage is reported "
        "separately and is *not* optimised by the allocator.",
        "",
    ]
    return "\n".join(lines)


def _op_domain(artifact: dict[str, Any], kernel_label: str) -> tuple[str, str]:
    """Return the (op_type, domain) of the node implementing the named kernel.

    The graph may contain more nodes than the kernel (e.g. int8 dynamic quantization wraps
    ``MatMulInteger`` in ``DynamicQuantizeLinear``/``Mul``/``Cast``), so pick the node whose op type
    matches the kernel label rather than the first node.
    """
    op_name = kernel_label.split(" ")[0]
    for node in artifact["nodes"]:
        if node["op_type"] == op_name:
            return node["op_type"], node["domain"] or "(default)"
    node = artifact["nodes"][0]
    return node["op_type"], node["domain"] or "(default)"


def table_class4cpu_bytes() -> str:
    doc = _load(CLASS4CPU)
    lines = [
        _banner(
            "Class-4-CPU measured container bytes (Milestone 2/6 fixture)",
            CLASS4CPU,
            f"Substrate `{doc['substrate']}`; measurement class **{doc['measurement_class']}** "
            f"(kernel: {doc['backend']['kernels']}, provider {doc['backend']['execution_provider']}, "
            f"dequantized_path={str(doc['backend']['dequantized_path']).lower()}). "
            "Class-3 byte measurement; every file the save produced is summed.",
        ),
        "| backend | op / domain | graph B | sidecar B | payload B | scales B | zero-point B | "
        "overhead B | total B (class 3) | bits/param measured |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    kernels = doc["backend"]["kernels"]
    for key in ("fp32", "int4", "int8"):
        artifact = doc["artifacts"][key]
        byte = artifact["bytes"]
        op_type, domain = _op_domain(artifact, kernels.get(key, artifact["nodes"][0]["op_type"]))
        bits = doc["reconciliation"][key]["measured_bits_per_param"]
        lines.append(
            f"| `{artifact['backend']}` | {op_type} / {domain} | {byte['graph_bytes']} | "
            f"{byte['sidecar_bytes']} | {byte['payload_bytes']} | {byte['scales_bytes']} | "
            f"{byte['zero_point_bytes']} | {byte['container_overhead_bytes']} | "
            f"{byte['total_bytes']} | {_num(bits)} |"
        )
    lines += [
        "",
        "## Analytical (class 1) vs measured (class 3) reconciliation",
        "",
        "| artifact | analytical B | measured B | residual B | of which scale-dtype | "
        "of which container |",
        "|---|---|---|---|---|---|",
    ]
    for key in ("fp32", "int4", "int8"):
        rec = doc["reconciliation"][key]
        lines.append(
            f"| {key} | {rec['analytical_total_bytes']} | {rec['measured_total_bytes']} | "
            f"{rec['residual_bytes']} | {rec['scale_dtype_delta_bytes']} | "
            f"{rec['container_overhead_bytes']} |"
        )
    lines += [
        "",
        "The residual is expected and decomposed (the analytical model has no graph/file overhead; "
        "ONNX Runtime writes fp32 scales where the accounting model uses fp16). The container "
        "overhead term is measured per artifact, never assumed.",
        "",
    ]
    return "\n".join(lines)


def table_class4cpu_latency() -> str:
    doc = _load(CLASS4CPU)
    lines = [
        _banner(
            "Class-4-CPU latency table (protocol compliance, not a performance claim)",
            CLASS4CPU,
            "> " + doc["scope_line"],
        ),
        f"timer `{doc['protocol']['timer']}`, sync `{doc['protocol']['sync_method']}`, "
        f"{doc['protocol']['warmup_iters']} warm-ups, {doc['protocol']['repeats']} repeats; "
        f"threads {doc['threads']['effective']} on {doc['threads']['cpu_model']}. "
        "p95 is indicative at 5 samples; read the median and the min/max/IQR.",
        "",
        "| X shape | backend | median ns | p95 ns | min ns | max ns | IQR ns | samples | threads |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for workload in doc["workloads"]:
        latency = workload["latency"]
        shape = f"({workload['shape_batch_x_K'][0]}, {workload['shape_batch_x_K'][1]})"
        lines.append(
            f"| {shape} | `{workload['backend']}` | {_num(latency['median_ns'])} | "
            f"{_num(latency['p95_ns'])} | {_num(latency['min_ns'])} | {_num(latency['max_ns'])} | "
            f"{_num(latency['iqr_ns'])} | {latency['samples']} | {workload['threads']['effective']} |"
        )
    lines += [
        "",
        "**No speedup is claimed or implied.** At these shapes the absolute latency is dominated by "
        "ONNX Runtime session-call overhead, so the table's value is protocol compliance: it shows "
        "the kernels execute our containers under a controlled, disclosed protocol with a "
        "same-session fp32 baseline.",
        "",
    ]
    return "\n".join(lines)


def table_regularizer_arms() -> str:
    doc = _load(REGULARIZER)
    lines = [
        _banner(
            "Regularizer arms (Milestone 5, exploratory Tier-0 fixture)",
            REGULARIZER,
            f"Status **{doc['status']}**; substrate `{doc['substrate']}`; H3 confirmatory cell "
            f"`{doc['confirmatory_cell']['substrate']}` **{doc['confirmatory_cell']['status']}**. "
            "Mean +/- sd over seeds; all arms share one compression plan, so class-1 accounted bytes "
            "are equal by construction.",
        ),
        "| cell | group | dev NLL (quantized) | output err vs dense | factor rounding residual | "
        "product rounding residual | accounted B (class 1) |",
        "|---|---|---|---|---|---|---|",
    ]
    for name, cell in doc["cells"].items():
        metrics = cell["metrics"]
        lines.append(
            f"| `{name}` | {cell['group']} | {_mean_sd(metrics, 'dev_nll_quantized')} | "
            f"{_mean_sd(metrics, 'output_error_vs_dense')} | "
            f"{_mean_sd(metrics, 'factor_rounding_residual')} | "
            f"{_mean_sd(metrics, 'product_rounding_residual')} | {cell['accounted_bytes']} |"
        )
    lines += [
        "",
        "## Predeclared arm contrast (unprepared `none` vs `full`)",
        "",
        "The `none` and `full` columns are artifact values; the **relative change** column is derived "
        "from them (not stored in the artifact).",
        "",
        "| quantity | `none` | `full` | relative change |",
        "|---|---|---|---|",
    ]
    for key, label in (
        ("dev_nll_quantized", "dev NLL (quantized)"),
        ("output_error_vs_dense", "output err vs dense"),
        ("factor_rounding_residual", "factor rounding residual"),
        ("product_rounding_residual", "product rounding residual"),
    ):
        base = doc["cells"]["none"]["metrics"][key]["mean"]
        full = doc["cells"]["full"]["metrics"][key]["mean"]
        change = (full - base) / base
        lines.append(f"| {label} | {base:.6g} | {full:.6g} | {change:+.2%} |")
    lines += [
        "",
        "The two quality axes disagree in sign on this fixture: the unregularized `none` arm has the "
        "best dev NLL and the worst fidelity-to-dense. H3 is **not supported** locally, and the "
        "confirmatory cell is NOT RUN. See `docs/results/regularizer-report.md`.",
        "",
    ]
    return "\n".join(lines)


def table_proxy_fixture() -> str:
    doc = _load(PROXY_FIXTURE)
    fixture_names = list(doc["fixtures"])
    proxies = list(doc["fixtures"][fixture_names[0]]["proxies"])
    lines = [
        _banner(
            "Proxy fixture ranking (Milestone 2, single seed)",
            PROXY_FIXTURE,
            "Spearman rho between each proxy's per-layer score and the measured single-layer damage "
            "(class 2, `LOCAL-FIXTURE`). One seed, one `(rank=8, bits=4)` configuration, 13 modules.",
        ),
        "| proxy | " + " | ".join(f"rho ({name})" for name in fixture_names) + " | "
        "joint/Sum proxy (layernorm) |",
        "|---|---|" + "---|" * len(fixture_names),
    ]
    for proxy in proxies:
        cells = [
            _num(doc["fixtures"][name]["proxies"][proxy]["spearman_vs_single_layer_damage"], 3)
            for name in fixture_names
        ]
        joint = _num(doc["fixtures"][fixture_names[0]]["proxies"][proxy]["joint_over_sum_proxy"], 3)
        lines.append(f"| `{proxy}` | " + " | ".join(cells) + f" | {joint} |")
    damage = doc["fixtures"]["layernorm"]["damage"]
    lines += [
        "",
        f"Joint damage / Sum(single-layer damage) = {damage['joint_over_sum_single']:.6f} "
        "(layernorm) and "
        f"{doc['fixtures']['no_layernorm']['damage']['joint_over_sum_single']:.6f} (no_layernorm): "
        "per-layer damage composes super-additively here.",
        "",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------------------------
# Figure
# --------------------------------------------------------------------------------------------
def figure_pareto() -> str:
    doc = _load(FRONTIER)
    points: list[tuple[float, float, str, int]] = []
    for point in doc["points"]:
        for solver in _SOLVER_ORDER:
            arm = point["arms"][solver]
            points.append(
                (
                    float(arm["measured_bytes"]),
                    float(arm["measured_hidden_damage"]),
                    solver,
                    int(point["budget_bytes"]),
                )
            )
    width, height = 900, 620
    margin = {"left": 90, "right": 220, "top": 70, "bottom": 80}
    plot_w = width - margin["left"] - margin["right"]
    plot_h = height - margin["top"] - margin["bottom"]
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    x_min, x_max = min(xs) * 0.9, max(xs) * 1.05
    y_min, y_max = 0.0, max(ys) * 1.08

    def sx(value: float) -> float:
        return margin["left"] + (value - x_min) / (x_max - x_min) * plot_w

    def sy(value: float) -> float:
        return margin["top"] + plot_h - (value - y_min) / (y_max - y_min) * plot_h

    parts: list[str] = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" font-family="Helvetica, Arial, sans-serif">',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        f'<text x="{width / 2:.0f}" y="30" text-anchor="middle" font-size="19" '
        'font-weight="bold">Allocator frontier: measured hidden-state damage vs measured bytes</text>',
        f'<text x="{width / 2:.0f}" y="52" text-anchor="middle" font-size="12" fill="#555">'
        "Substrate LOCAL-FIXTURE (one seed, 13 modules, synthetic task) | classes 1/2/3 | "
        "NOT the confirmatory H4 cell (NOT RUN)</text>",
    ]
    # Axes
    parts.append(
        f'<line x1="{margin["left"]}" y1="{margin["top"]}" x2="{margin["left"]}" '
        f'y2="{margin["top"] + plot_h}" stroke="#333" stroke-width="1.2"/>'
    )
    parts.append(
        f'<line x1="{margin["left"]}" y1="{margin["top"] + plot_h}" '
        f'x2="{margin["left"] + plot_w}" y2="{margin["top"] + plot_h}" stroke="#333" '
        'stroke-width="1.2"/>'
    )
    for tick_bytes in doc["budgets"]["ladder_bytes"]:
        x = sx(float(tick_bytes))
        parts.append(
            f'<line x1="{x:.1f}" y1="{margin["top"] + plot_h}" x2="{x:.1f}" '
            f'y2="{margin["top"] + plot_h + 5}" stroke="#333"/>'
        )
        parts.append(
            f'<text x="{x:.1f}" y="{margin["top"] + plot_h + 20}" text-anchor="middle" '
            f'font-size="11">{tick_bytes}</text>'
        )
    for frac in (0.0, 0.25, 0.5, 0.75, 1.0):
        value = y_min + frac * (y_max - y_min)
        y = sy(value)
        parts.append(
            f'<line x1="{margin["left"] - 5}" y1="{y:.1f}" x2="{margin["left"]}" '
            f'y2="{y:.1f}" stroke="#333"/>'
        )
        parts.append(
            f'<text x="{margin["left"] - 8}" y="{y + 4:.1f}" text-anchor="end" font-size="11">'
            f"{value:.2f}</text>"
        )
    parts += [
        f'<text x="{margin["left"] + plot_w / 2:.0f}" y="{height - 38}" text-anchor="middle" '
        'font-size="13">measured stored bytes (class 3)</text>',
        f'<text transform="translate(24,{margin["top"] + plot_h / 2:.0f}) rotate(-90)" '
        'text-anchor="middle" font-size="13">measured hidden-state damage (class 2)</text>',
    ]
    # Equal-memory wins: draw a connector between the uniform point and the winning mixed point.
    for win in doc["equal_memory_wins"]:
        budget = int(win["budget_bytes"])
        reference = next(p for p in doc["points"] if p["budget_bytes"] == budget)["arms"]["uniform"]
        mixed = next(p for p in doc["points"] if p["budget_bytes"] == budget)["arms"][
            win["candidate"]
        ]
        parts.append(
            f'<line x1="{sx(float(reference["measured_bytes"])):.1f}" '
            f'y1="{sy(float(reference["measured_hidden_damage"])):.1f}" '
            f'x2="{sx(float(mixed["measured_bytes"])):.1f}" '
            f'y2="{sy(float(mixed["measured_hidden_damage"])):.1f}" stroke="#999" '
            'stroke-width="1" stroke-dasharray="4 3"/>'
        )
        parts.append(
            f'<text x="{(sx(float(reference["measured_bytes"])) + sx(float(mixed["measured_bytes"]))) / 2:.1f}" '
            f'y="{(sy(float(reference["measured_hidden_damage"])) + sy(float(mixed["measured_hidden_damage"]))) / 2 - 6:.1f}" '
            f'text-anchor="middle" font-size="10" fill="#666">'
            f"{win['candidate']} {win['budget_bytes']}B ratio {win['hidden_damage_ratio']:.3f}</text>"
        )
    # Markers
    for x_value, y_value, solver, budget in points:
        parts.append(
            f'<circle cx="{sx(x_value):.1f}" cy="{sy(y_value):.1f}" r="5" '
            f'fill="{_SOLVER_COLORS[solver]}" stroke="#222" stroke-width="0.6">'
            f"<title>{solver}: budget {budget} B, measured {x_value:.0f} B, "
            f"hidden damage {y_value:.4f}</title></circle>"
        )
    # Legend
    legend_x = width - margin["right"] + 30
    parts.append(
        f'<text x="{legend_x}" y="{margin["top"]}" font-size="13" font-weight="bold">solver</text>'
    )
    for index, solver in enumerate(_SOLVER_ORDER):
        y = margin["top"] + 24 + index * 22
        parts.append(
            f'<circle cx="{legend_x}" cy="{y - 4}" r="5" fill="{_SOLVER_COLORS[solver]}" '
            'stroke="#222" stroke-width="0.6"/>'
        )
        parts.append(f'<text x="{legend_x + 14}" y="{y}" font-size="12">{solver}</text>')
    parts.append(
        f'<text x="{legend_x}" y="{margin["top"] + 110}" font-size="11" fill="#555">'
        "dashed line: equal-memory</text>"
    )
    parts.append(
        f'<text x="{legend_x}" y="{margin["top"] + 126}" font-size="11" fill="#555">'
        "uniform-vs-mixed win</text>"
    )
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


# --------------------------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------------------------
TABLES: dict[str, Any] = {
    "proxy-ranking.md": table_proxy_ranking,
    "allocator-frontier.md": table_allocator_frontier,
    "class4cpu-bytes.md": table_class4cpu_bytes,
    "class4cpu-latency.md": table_class4cpu_latency,
    "regularizer-arms.md": table_regularizer_arms,
    "proxy-fixture.md": table_proxy_fixture,
}
FIGURES: dict[str, Any] = {
    "pareto-damage-vs-bytes.svg": figure_pareto,
}


def generate(out_dir: Path) -> list[Path]:
    """Write every table and figure under ``out_dir``; return the written paths."""
    tables_dir = out_dir / "tables"
    figures_dir = out_dir / "figures"
    tables_dir.mkdir(parents=True, exist_ok=True)
    figures_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for filename, builder in TABLES.items():
        target = tables_dir / filename
        target.write_text(builder(), encoding="utf-8", newline="\n")
        written.append(target)
    for filename, builder in FIGURES.items():
        target = figures_dir / filename
        target.write_text(builder(), encoding="utf-8", newline="\n")
        written.append(target)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out", type=Path, default=DEFAULT_OUT, help="output root (default: reports/)"
    )
    args = parser.parse_args(argv)
    written = generate(args.out)
    for path in written:
        print(path.relative_to(REPO_ROOT) if path.is_relative_to(REPO_ROOT) else path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
